#!/usr/bin/env python3
"""Generate a trimmed pyproject.toml for the published skill bundle.

The skill ships everything under skill_gather/ except mcp/, because the MCP
server is a separate delivery channel that needs a host process. Copying the
main pyproject.toml verbatim into the bundle causes two concrete problems:

  1. `[project.scripts] skill-gather-mcp` points at skill_gather.mcp.server,
     which is not present in the bundle — a dangling entry point.
  2. The `mcp` dependency drags in starlette, uvicorn, sse-starlette and friends.
     Measured effect: the skill's venv grew to ~50 MB installing an HTTP server
     stack for code that cannot run in the bundle.

Rather than maintaining a second pyproject.toml by hand (which would drift), we
derive it from the real one and strip exactly what the bundle excludes.

Uses only the standard library so it runs on a bare CI image.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

# Dependencies to drop, matched on the distribution name at the start of the
# requirement string. These exist solely for the excluded mcp/ package.
_DROP_DEPENDENCIES = {"mcp"}

# Console scripts to drop, matched on the entry-point name.
_DROP_SCRIPTS = {"skill-gather-mcp"}

_HEADER = """# Generated by scripts/build_skill_pyproject.py - do not edit.
#
# Trimmed copy of the project's pyproject.toml for the published skill bundle.
# The bundle excludes skill_gather/mcp/, so the `mcp` dependency and the
# `skill-gather-mcp` entry point are removed to avoid a dangling script and a
# large unused dependency tree.
"""


def _requirement_name(requirement: str) -> str:
    """Extract the distribution name from a PEP 508 requirement string."""
    return re.split(r"[\s\[<>=!~;]", requirement.strip(), maxsplit=1)[0].lower()


def _quote(value: str) -> str:
    """Emit a TOML basic string, escaping what TOML requires."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build(source: Path, output: Path) -> int:
    if not source.exists():
        print(f"ERROR: source not found: {source}", file=sys.stderr)
        return 1

    data = tomllib.loads(source.read_text(encoding="utf-8"))
    project = data.get("project")
    if not project:
        print(f"ERROR: no [project] table in {source}", file=sys.stderr)
        return 1

    # --- dependencies ---------------------------------------------------
    kept_deps: list[str] = []
    dropped_deps: list[str] = []
    for requirement in project.get("dependencies", []):
        if _requirement_name(requirement) in _DROP_DEPENDENCIES:
            dropped_deps.append(requirement)
        else:
            kept_deps.append(requirement)

    # --- console scripts ------------------------------------------------
    kept_scripts: dict[str, str] = {}
    dropped_scripts: list[str] = []
    for name, target in (project.get("scripts") or {}).items():
        if name in _DROP_SCRIPTS:
            dropped_scripts.append(name)
        else:
            kept_scripts[name] = target

    # Fail loudly if the thing we are supposed to remove is not there. Silently
    # succeeding would mean the trimming logic has drifted from the real
    # pyproject.toml and the bundle is shipping the bloat again.
    if not dropped_deps:
        print(
            f"ERROR: expected to drop {sorted(_DROP_DEPENDENCIES)} from dependencies "
            "but found none. Update _DROP_DEPENDENCIES if the layout changed.",
            file=sys.stderr,
        )
        return 1
    if not dropped_scripts:
        print(
            f"ERROR: expected to drop {sorted(_DROP_SCRIPTS)} from [project.scripts] "
            "but found none. Update _DROP_SCRIPTS if the layout changed.",
            file=sys.stderr,
        )
        return 1

    # --- render ---------------------------------------------------------
    lines: list[str] = [_HEADER, "[project]"]
    lines.append(f"name = {_quote(project['name'])}")
    lines.append(f"version = {_quote(project['version'])}")
    if project.get("description"):
        lines.append(f"description = {_quote(project['description'])}")
    if project.get("requires-python"):
        lines.append(f"requires-python = {_quote(project['requires-python'])}")

    lines.append("dependencies = [")
    for requirement in kept_deps:
        lines.append(f"    {_quote(requirement)},")
    lines.append("]")

    if kept_scripts:
        lines.append("")
        lines.append("[project.scripts]")
        for name, target in kept_scripts.items():
            lines.append(f"{name} = {_quote(target)}")

    build_system = data.get("build-system")
    if build_system:
        lines.append("")
        lines.append("[build-system]")
        requires = build_system.get("requires", [])
        lines.append(
            "requires = [" + ", ".join(_quote(r) for r in requires) + "]"
        )
        if build_system.get("build-backend"):
            lines.append(f"build-backend = {_quote(build_system['build-backend'])}")

    wheel = (
        data.get("tool", {})
        .get("hatch", {})
        .get("build", {})
        .get("targets", {})
        .get("wheel")
    )
    if wheel and wheel.get("packages"):
        lines.append("")
        lines.append("[tool.hatch.build.targets.wheel]")
        lines.append(
            "packages = [" + ", ".join(_quote(p) for p in wheel["packages"]) + "]"
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {output}")
    print(f"  dependencies kept   : {len(kept_deps)}")
    print(f"  dependencies dropped: {', '.join(dropped_deps)}")
    print(f"  scripts kept        : {', '.join(kept_scripts) or 'none'}")
    print(f"  scripts dropped     : {', '.join(dropped_scripts)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    return build(args.source, args.output)


if __name__ == "__main__":
    sys.exit(main())
