"""Update README.md with live stats from registry/meta.json.

Replaces the content between <!-- REGISTRY-STATS-START --> and
<!-- REGISTRY-STATS-END --> markers with freshly generated statistics.

Run after every sync:
    uv run python scripts/update_readme.py
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
META_PATH = ROOT / "registry" / "meta.json"
README_PATH = ROOT / "README.md"

MARKER_START = "<!-- REGISTRY-STATS-START -->"
MARKER_END = "<!-- REGISTRY-STATS-END -->"


def load_meta() -> dict:
    if not META_PATH.exists():
        print(f"ERROR: {META_PATH} not found — run skill-gather sync first", file=sys.stderr)
        sys.exit(1)
    with open(META_PATH, encoding="utf-8") as f:
        return json.load(f)


def render_stats_block(meta: dict) -> str:
    total = meta.get("total_skills", 0)
    sources_count = meta.get("sources_count", 0)
    last_synced_raw = meta.get("last_synced", "")
    changelog = meta.get("changelog", {})

    # Format last synced date
    try:
        dt = datetime.fromisoformat(last_synced_raw.replace("Z", "+00:00"))
        last_synced = dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        last_synced = last_synced_raw or "unknown"

    # Category breakdown (top 5)
    categories = meta.get("categories", {})
    top_cats = sorted(categories.items(), key=lambda x: -x[1])[:5]
    cat_lines = " · ".join(f"{cat} `{count}`" for cat, count in top_cats)

    # Platform breakdown
    platform_counts = meta.get("platform_counts", {})
    plat_parts = []
    plat_labels = {
        "claude_code": "Claude Code",
        "kiro": "Kiro",
        "codex": "Codex",
        "claude_ai": "Claude.ai",
        "universal": "Universal",
    }
    for key, label in plat_labels.items():
        count = platform_counts.get(key, 0)
        if count:
            plat_parts.append(f"{label} `{count}`")
    plat_line = " · ".join(plat_parts)

    # Source list
    sources = meta.get("sources", [])
    source_lines = "\n".join(f"  - `{s}`" for s in sources)

    # Changelog summary
    cl = changelog or {}
    added = cl.get("added", 0)
    removed = cl.get("removed", 0)
    modified = cl.get("modified", 0)
    if any([added, removed, modified]):
        cl_line = f"Last sync changes: +{added} added / -{removed} removed / ~{modified} modified"
    else:
        cl_line = "Last sync: no changes detected"

    block = f"""{MARKER_START}
<!-- Auto-generated by scripts/update_readme.py — do not edit manually -->

## Registry Stats

| | |
|---|---|
| **Total Skills** | {total} |
| **Data Sources** | {sources_count} |
| **Last Synced** | {last_synced} |

**By Category** (top 5): {cat_lines}

**Platform Compatibility**: {plat_line}

**Active Sources**:
{source_lines}

> {cl_line}

{MARKER_END}"""
    return block


def update_readme(stats_block: str) -> None:
    content = README_PATH.read_text(encoding="utf-8")

    if MARKER_START in content and MARKER_END in content:
        # Replace existing block
        pattern = re.compile(
            re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
            re.DOTALL,
        )
        new_content = pattern.sub(stats_block, content)
    else:
        # Append to end of file
        new_content = content.rstrip() + "\n\n" + stats_block + "\n"

    README_PATH.write_text(new_content, encoding="utf-8")
    print(f"README.md updated with stats ({META_PATH.stat().st_size} bytes meta)")


def main() -> None:
    meta = load_meta()
    block = render_stats_block(meta)
    update_readme(block)


if __name__ == "__main__":
    main()
